services:
  mongo:
    image: mongo:latest
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=114514
      - TZ=Asia/Shanghai
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=114514
  worker:
    build: ./worker/
    container_name: worker
    restart: always
    depends_on:
      - mongo
      - rabbit
  api:
    build: .
    container_name: api
    expose:
      - "8080"
    restart: always
    depends_on:
      - mongo
      - rabbit
      - worker
