# .github/workflows/rust.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build-main:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main binary
          path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          compression-level: 0
  build-worker:
    name: Build worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          SRC_DIR: "worker"
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Worker binary
          path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          compression-level: 0
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: ["build-main", "build-worker"]
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v4

      - name: Decompress main artifact
        run: |
          ls -l
          mkdir main_dir
          mkdir worker_dir
          unzip "Main binary" -d "main_dir/"
          unzip "Worker binary" -d "worker_dir/"
          ls -l
          unzip "main_dir/hust_ledger_back_null_x86_64-unknown-linux-musl.zip"
          unzip "worker_dir/hust_ledger_back_null_x86_64-unknown-linux-musl.zip"
          ls -l

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            "hust_ledger_back"
            "worker"
