# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]

jobs:
  build-main:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Main binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  build-worker:
    name: Build worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          SRC_DIR: "worker"
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Worker binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
